#!/bin/bash

SERVER_LOCATION=/home/filip/Dropbox/ClojureProjects/imp-rest/

#################
#---FUNCTIONS---#
#################

function run_server {

cd $SERVER_LOCATION

#lein run
heroku local

}

##############
#---SCRIPT---#
##############

npm run dist

cp dist/index.html $SERVER_LOCATION/resources/public/index.html
cp dist/index_bundle.js $SERVER_LOCATION/resources/public/index_bundle.js

run_server

exit 0
